# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('stream', models.CharField(choices=[('cse', 'Computer Science'), ('ece', 'Electronics and Communication'), ('mae', 'Mechanical and Automation'), ('it', 'Information Technology'), ('eee', 'Electrical and Electronics')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sessional', models.IntegerField()),
                ('second_sessional', models.IntegerField()),
                ('internal_assessment', models.IntegerField()),
                ('total_internal_marks', models.IntegerField()),
                ('internal_practical', models.IntegerField()),
                ('external_practical', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('roll_no', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=12)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=12)),
                ('batches', models.ManyToManyField(to='marks.Batch')),
                ('subjects', models.ManyToManyField(to='marks.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='marks.Subject'),
        ),
        migrations.AddField(
            model_name='marks',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Student'),
        ),
        migrations.AddField(
            model_name='marks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Subject'),
        ),
    ]
