# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_auto_20160225_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('stream', models.CharField(choices=[('cse', 'Computer Science'), ('ece', 'Electronics and Communication'), ('mae', 'Mechanical and Automation'), ('it', 'Information Technology'), ('eee', 'Electrical and Electronics')], max_length=3)),
                ('subjects', models.ManyToManyField(to='marks.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='marks.Course'),
            preserve_default=False,
        ),
    ]
