# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0005_auto_20160410_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Batch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='batches',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teachersubject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Teacher'),
        ),
    ]
