# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0006_auto_20160410_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
    ]
