# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0007_remove_student_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherSubject',
            new_name='BatchSubject',
        ),
    ]
