# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0008_auto_20160410_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='external_practical',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='first_sessional',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='internal_assessment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='internal_practical',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='second_sessional',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='marks',
            name='total_internal_marks',
            field=models.IntegerField(null=True),
        ),
    ]
