# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0009_auto_20160410_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
