# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0011_auto_20160423_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Batch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.Teacher')),
            ],
        ),
    ]
